export const images = {
    splash: require('./splash-bg.png'),
    noConnection: require('./no-connection.png'),
    closeModal: require('./close-modal.png'),
    loginLogo: require('./logo-login.png'),
    cart: require('./cart.png'),
    addToCart: require('./add-to-cart.png'),
    addedToCart: require('./added-to-cart.png'),
    exit: require('./exit.png'),
    delete: require('./delete.png'),
    blueCart: require('./blue-cart.png'),
    detailsIcon: require('./details-icon.png'),
    back: require('./back.png'),
    icon360: require('./360-icon.png'),
    plusBig: require('./plus-big.png'),
    pdfIcon: require('./pdf-icon.png'),
    minus: require('./minus.png'),
    plus: require('./plus-1.png'),
    edit: require('./edit.png'),
};
